# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create( name: "Cool Bird", description: "What can we say about this bird that hasn't already been said", birdtype: "good", price: "5000", image_url: "1.jpg" )
Product.create( name: "Solid Bird", description: "Good, solid bird. Does bird things.", birdtype: "good", price: "6000", image_url: "2.jpg" )
Product.create( name: "Mean Bird", description: "We caught this bird stealing from old people,", birdtype: "Bad", price: "40", image_url: "3.jpg" )
Product.create( name: "Arrogant Bird", description: "He thinks he is cooler than you, pretty annoying.", birdtype: "Expensive", price: "99599", image_url: "4.jpg" )
Product.create( name: "Stupid Bird", description: "Not the smartest bird, but a bargain. BOGO!", birdtype: "Dumb", price: "580", image_url: "5.jpg" )
Product.create( name: "Big Bird", description: "No joke, this bird is a champ.", birdtype: "Expensive", price: "987520", image_url: "6.jpg")
Product.create( name: "Lazy Bird", description: "This bird never helps with housework.", birdtype: "Bad", price: "1000", image_url: "7.jpg" )
Product.create( name: "Basic Bird", description: "Nothing special about this bird. Not bad, not great.", birdtype: "Cheap", price: "35000", image_url: "8.jpg" )
Product.create( name: "Sneaky Bird", description: "You will love this bird, but may not be able to find it. ", birdtype: "Good", price: "658800", image_url: "9.jpg" )
Product.create( name: "Terrible Bird", description: "Just some bird, we don't recommend him.", birdtype: "Bad", price: "1200", image_url: "10.jpg" )
Product.create( name: "Pretty Bird", description: "This bird is pretty, and nice.", birdtype: "good", price: "4200", image_url: "11.jpg" )
Product.create( name: "Tiny Bird", description: "Portable and affordable, kind of smart too. ", birdtype: "Smart", price: "8700", image_url: "12.jpg" )
Product.create( name: "Woke Bird", description: "This bird can tell you all about the fibonacci sequence.", birdtype: "Cheap", price: "580", image_url: "13.jpg" )
Product.create( name: "Normal Bird", description: "Boring, but reliable, this bird might be right for you. ", birdtype: "Cheap", price: "985", image_url: "14.jpg" )
Product.create( name: "Crazy Bird", description: "Watch out for this bird, you don't know what he might do next.", birdtype: "Bad", price: "2999", image_url: "15.jpg" )
Product.create( name: "Awful Bird", description: "Please be careful with this bird! He might insult you.", birdtype: "Bad", price: "87", image_url: "16.jpg" )
Product.create( name: "Sad Bird", description: "This bird needs a hug.", birdtype: "good", price: "10000", image_url: "17.jpg" )
Product.create( name: "Creative Bird", description: "We once saw this bird write a screenplay, it was decent!", birdtype: "Smart", price: "1589", image_url: "18.jpg" )
Product.create( name: "Ignorant Bird", description: "Has no awareness of current issues.", birdtype: "Cheap", price: "120", image_url: "19.jpg" )
Product.create( name: "Small Bird", description: "Small birds are extra portable, reliable, and good at math.", birdtype: "good", price: "3500", image_url: "20.jpg" )
Product.create( name: "Dead Bird", description: "This bird is dead.", birdtype: "Cheap", price: "50", image_url: "21.jpg" )
Product.create( name: "Fancy Bird", description: "Make an entrance they won't forget with this bird.", birdtype: "Expensive", price: "100000", image_url: "22.jpg" )
Product.create( name: "Short Bird", description: "What this bird lacks in height, he makes up for in cunning. ", birdtype: "Smart", price: "4895", image_url: "23.jpg" )
Product.create( name: "Incredible Bird", description: "Our customers have only great things to say about this bird.", birdtype: "Expensive", price: "1600000", image_url: "24.jpg" )
Product.create( name: "Light Bird", description: "It is like you can't even tell if you are holding him.", birdtype: "good", price: "5400", image_url: "25.jpg" )
Product.create( name: "Jealous Bird", description: "He is very untrusting, don't let him see you with another bird.", birdtype: "Bad", price: "58", image_url: "26.jpg" )
Product.create( name: "Premium Bird", description: "Top shelf, serious buyers only. ", birdtype: "Expensive", price: "589586", image_url: "27.jpg" )
Product.create( name: "Philosophical Bird", description: "He is into Nietzsche and Kafke.", birdtype: "Smart", price: "85500", image_url: "28.jpg" )
Product.create( name: "Impressive Bird", description: "Very good bird, show off to your friends. Not humble about it though. ", birdtype: "good", price: "10000", image_url: "29.jpg" )
Product.create( name: "Wet Bird", description: "Has trouble drying off, has a strong odor as well. ", birdtype: "Bad", price: "870", image_url: "30.jpg" )
Product.create( name: "Annoying Bird", description: "We can't get this bird to be quiet, but he is a bargain. ", birdtype: "Cheap", price: "75", image_url: "31.jpg" )
Product.create( name: "Tired Bird", description: "Needs a nap, and a shower. ", birdtype: "Bad", price: "20", image_url: "32.jpg" )
Product.create( name: "Ugly Bird", description: "But you don't have to be mean about it.", birdtype: "Cheap", price: "0.01", image_url: "33.jpg" )
Product.create( name: "Fast Bird", description: "So fast, so good, much bird.", birdtype: "Expensive", price: "50000", image_url: "34.jpg" )
Product.create( name: "Slow Bird", description: "So slow, not great, still a bird.", birdtype: "Cheap", price: "99", image_url: "35.jpg" )
Product.create( name: "Angry Bird", description: "No not like the game, he is actually pretty upset.", birdtype: "Bad", price: "870", image_url: "36.jpg" )
Product.create( name: "Special Bird", description: "Just wow.", birdtype: "Expensive", price: "878787", image_url: "37.jpg" )
Product.create( name: "Bad Bird", description: "Cheats on his taxes, takes handicap parking spots.", birdtype: "Bad", price: "1225", image_url: "38.jpg" )
Product.create( name: "Suspicious Bird", description: "We just aren't sure what he is up to, we are worried.", birdtype: "Bad", price: "2200", image_url: "39.jpg" )
Product.create( name: "Clever Bird", description: "Solves puzzles, codes software, has a startup. ", birdtype: "Smart", price: "6550", image_url: "40.jpg" )
Product.create( name: "Confused Bird", description: "Help this bird out, he has trouble with decisions.", birdtype: "Dumb", price: "587", image_url: "41.jpg" )
Product.create( name: "Cute Bird", description: "Freakin' adorable, you can't go wrong with this bird. ", birdtype: "good", price: "9999", image_url: "42.jpg" )
